### ISSUE TITLE
Step by step tutorial?

### ISSUE THREAD

**Issue by gitihobo** [ni5arga/azlyrics-scraper#1]
I cant seem to make it work, it only outputs blank spaces

**Comment by ni5arga** [comment]
I updated the code in the last commit, is it working for you now?

**Comment by ni5arga** [comment]
I updated the code in the last commit, is it working for you now?

**Comment by gitihobo** [comment]
Works great thank you! Think you can make another scraper based on an image website? Like pinterest?

**Comment by ni5arga** [comment]
Welcome! I'll try to work on them in the future!
